import './globals.css';
import { Inter, Roboto } from 'next/font/google';
import Providers from './provider';
import Nav from '@/Components/Nav';
import Sidebar from '@/Components/Sidebar';
import MobileNav from '@/UI/MobileNav';

const inter = Inter({ subsets: ['latin'] });
const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.className} overflow-hidden`}>
        <Providers>
          <Nav />
          <div className="h-screen  pb-16 ">
            {/* <Sidebar /> */}
            {children}
          </div>
          <MobileNav />
        </Providers>
      </body>
    </html>
  );
}
